server:
  port: 9090

spring:
  application:
    name: indicadores
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: mysecretpassword

  jpa:
    hibernate:
      ddl-auto: update